### ISSUE TITLE
link to blog in readme doesn't work

### ISSUE THREAD

**Issue by carusog** [salvozappa/salvatorezappala.info#1]
It seems like the HTTPS protocol, in readme link to blog, is not working. HTTP does. ;)

**Comment by salvozappa** [comment]
Thank you for pointing it out!

I'm aware of this, I'm migrating servers and the new one hasn't HTTPS configured yet. I'm planning to solve it to day.

**Comment by carusog** [comment]
I was sure something known. That's why no PR. 👍

**Comment by salvozappa** [comment]
Solved, closing. Thanks!
